{{- $bbtests := .Values.bbtests | default dict -}}
{{- $enabled := (hasKey $bbtests "enabled") -}}
{{- if $enabled }}
{{- if and .Values.networkPolicies.enabled .Values.bbtests.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-test-egress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      helm-test: enabled
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
      podSelector: {}
  policyTypes:
  - Egress
{{- end }}
{{- end }}
