{{- if and .Values.networkPolicies.enabled .Values.bbtests.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-tempo-allow-egress
  namespace: {{ .Release.Namespace }}
spec:
  policyTypes:
  - Egress
  podSelector:
    matchLabels:
      helm-test: enabled 
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
      podSelector:
        matchLabels:
          app.kubernetes.io/name: grafana
    ports:
    - port: 80
      protocol: TCP
    - port: 3000
      protocol: TCP
{{- end }}
