{{- if and .Values.networkPolicies.enabled (not (eq .Values.upstream.tempo.storage.backend "local")) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-external-services
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: 
    matchLabels:
      app.kubernetes.io/name: tempo
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
{{- end }}
