{{ if and .Values.networkPolicies.enabled .Values.sso.enabled }}
# Allow Traffic to authservice
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-tempo-authservice
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 10003
    to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: authservice
      namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: authservice
{{- end }}
