{{ if .Values.networkPolicies.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-tempo-zipkin
  namespace: {{ .Release.Namespace }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: tempo
  ingress:
  - ports:
    - port: 9411
{{- end }}
