{{- if and .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-alloy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: tempo
  policyTypes:
    - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: alloy
      podSelector:
        matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values:
              - alloy
              - alloy-alloy-logs
    ports:
      - port: 4317
        protocol: TCP
{{- end }}

