{{- if and .Values.networkPolicies.enabled .Values.istio.enabled }}
# Allow traffic from the IngressGateway to the tempo query UI
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-tempo-istio-igw
  namespace:  {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: tempo
  ingress:
  - ports:
    - port: 16686
      protocol: TCP
    from:
    - podSelector:
        matchLabels:
          {{- toYaml .Values.networkPolicies.ingressLabels | nindent 10}}
      namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: istio-controlplane
{{- end }}
