{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "tempo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tempo.name" . }}
    chart: {{ template "tempo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      name: {{ template "tempo.fullname" . }}
      app: {{ template "tempo.name" . }}
      release: {{ .Release.Name }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ template "client.name" . }}
            release: {{ .Release.Name }}
    - ports:
      - port: {{ .Values.service.port }}
{{- end }}
