{{- if and .Values.istio.enabled .Values.istio.tempoQuery.enabled .Values.tempo.searchEnabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tempo-query
  namespace: {{ .Release.Namespace }}
  labels:
  {{- if .Values.istio.tempoQuery.labels }}
{{ toYaml .Values.istio.tempoQuery.labels | indent 4 }}
  {{- end }}
  {{- if .Values.istio.tempoQuery.annotations }}
  annotations:
{{ toYaml .Values.istio.tempoQuery.annotations | indent 4 }}
  {{- end }}
spec:
  gateways:
  {{- range .Values.istio.tempoQuery.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.tempoQuery.hosts }}
    - {{ tpl . $}}
  {{- end }}
  http:
    - route:
        - destination:
            port:
              number: 16686
            host: {{ template "tempo.fullname" . }}
{{- end }}
