{{- if and (or .Values.sso.enabled .Values.istio.hardened.enabled) .Values.istio.enabled .Values.monitoring.enabled .Values.serviceMonitor.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: monitoring-ap
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" . | nindent 6 }}
  action: ALLOW
  # Allow all GET traffic on port 3100 and 16687 from monitoring ns to support both Grafana and Prometheus traffic
  rules:
  - from:
    - source:
        namespaces:
        - monitoring
        principals:
        - cluster.local/ns/monitoring/sa/monitoring-*
    to:
    - operation:
        methods:
        - GET
        ports:
        - "3100"
    - operation:
        methods:
        - GET
        ports:
        - "16687"
        - "16686"
  # Allow traffic to port 3100 and 16687 to support Prometheus' direct endpoint scraping, see https://github.com/istio/istio/issues/19975 for a discussion of this
  - to:
    - operation:
        ports:
        - "3100"
    - operation:
        ports:
        - "16687"
        - "16686"
{{- end }}
