{{- if and .Values.istio.enabled .Values.sso.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: tempo-ap
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - {{ .Release.Namespace }}
{{- end }}
