{{- if and .Values.istio.enabled (eq .Values.istio.mtls.mode "STRICT") .Values.monitoring.enabled .Values.serviceMonitor.enabled }}
apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: metrics-exceptions
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" . | nindent 6 }}
  portLevelMtls:
    "3100":
      mode: PERMISSIVE
{{- end }}
